// Sample Headers
let libraryHeaders = [
  { hidden: false, sort: {enablged: true}, name: '#', },
  { hidden: false, sort: {enablged: true}, name: 'TITLE', },
  { hidden: false, sort: {enablged: true}, name: 'ARTIST', },
  { hidden: false, sort: {enablged: true}, name: 'ALBUM', },
  { hidden: false, sort: {enablged: true}, name: 'YEAR', },
  { hidden: false, sort: {enablged: true}, name: 'DURATION', },
  { hidden: false, sort: {enablged: true}, name: 'GENRE', },
  { hidden: false, sort: {enablged: true}, name: 'PLAYLISTS', },
  { hidden: false, sort: {enablged: true}, name: 'TAGS' },
];

// Sample Catalog
let libraryCatalog = [
  { '#': '01', title: 'Future Nostalgia',       artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:05', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '02', title: 'Don\'t Start Now',       artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:03', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '03', title: 'Cool',                   artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:30', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '04', title: 'Physical',               artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:14', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '05', title: 'Levitating',             artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:24', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '06', title: 'Pretty Please',          artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:15', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '07', title: 'Hallucinate',            artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:29', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '08', title: 'Love Again',             artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '4:18', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '09', title: 'Break My Heart',         artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:42', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '10', title: 'Good In Bed (Explicit)', artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '3:39', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},
  { '#': '11', title: 'Boys Will Be Boys',      artist: 'Dua Lipa', album: 'Future Nostalgia', year: '2020', duration: '2:46', genre: 'Dance, Pop', playlists: 'Monday Songs, Summer Mix', tags: 'Party, Summer'},

  { '#': '01', title: 'United In Grief', artist: 'Kendrick Lamar',    album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '4:15', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '02', title: 'N95', artist: 'Kendrick Lamar',                album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '3:15', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '03', title: 'Worldwide Steppers', artist: 'Kendrick Lamar', album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '3:23', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '04', title: 'Die Hard', artist: 'Kendrick Lamar',           album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '3:59', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '05', title: 'Father Time', artist: 'Kendrick Lamar',        album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '3:42', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '06', title: 'Rich (Interlude)', artist: 'Kendrick Lamar',   album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '1:43', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '07', title: 'Rich Spirit', artist: 'Kendrick Lamar',        album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '3:22', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '08', title: 'We Cry Together', artist: 'Kendrick Lamar',    album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '5:41', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},
  { '#': '09', title: 'Purple Hearts', artist: 'Kendrick Lamar',      album: 'Mr. Morale & The Big Steppers', year: '2022', duration: '5:29', genre: 'Hip-Hop', playlists: 'Summer Mix, Vibe', tags: 'Conscious, Soulful'},

  { '#': '01', title: 'Come Together', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '4:21', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '02', title: 'Something', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '3:03', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '03', title: 'Maxwell\'s Silver Hammer', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '3:27', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '04', title: 'Oh! Darling', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '3:27', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '05', title: 'Octopus\'s Garden', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '2:51', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '06', title: 'I Want You (She\'s So Heavy)', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '7:47', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '07', title: 'Here Comes The Sun', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '3:05', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '08', title: 'Because', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '2:46', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '09', title: 'You Never Give Me Your Money', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '4:02', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '10', title: 'Sun King', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '2:27', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '11', title: 'Mean Mr. Mustard', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '1:06', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '12', title: 'Polythene Pam', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '1:13', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '13', title: 'She Came In Through The Bathroom Window', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '1:57', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '14', title: 'Golden Slumbers', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '1:32', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '15', title: 'Carry That Weight', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '1:37', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '16', title: 'The End', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '2:20', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
  { '#': '17', title: 'Her Majesty', artist: 'The Beatles', album: 'Abbey Road', year: '1969', duration: '0:23', genre: 'Rock', playlists: 'Fav Karaoke, Monday Songs', tags: 'Timeless, Jam'},
];