name: JSDOC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: install JSDOC
      run: npm install
      
    - name: Generate Template
      run: npm run tempUpdate --no-audit
        
    - name: Generate Docs
      run: npm run testJsDoc 
