name: JSDOC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
       working-directory: source/musicplayer
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
        
    - name: Generate Docs
      run: npm run docs 
